name: flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^0.13.6
#  google_fonts: ^4.0.4
  page_transition: ^2.0.9
  intl: ^0.17.0
  shared_preferences: ^2.1.0
#  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
#  lottie: ^2.3.2
#  shimmer: ^2.0.0
#  image_picker: ^0.8.5+3
#  permission_handler: ^10.1.0
#  dio: ^4.0.6
#  custom_refresh_indicator: ^2.0.1
  flutter_svg: ^2.0.5
#  flutter_svg_provider: ^1.0.3

flutter_assets_generator:
#  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
#  output_dir: generated
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: false
#  # Optional. Sets file name conversion rules. Default: true
#  named_with_parent: true
#  # Optional. Sets the name for the generated localization file. Default: assets
#  output_filename: assets
#  # Optional. Sets the name for the generated localization class. Default: Assets
#  class_name: Assets
#  # Optional. Sets the filename split pattern for filename split. Default: [-_]
#  filename_split_pattern: "[-_]"
#  # Optional. Configuring ignore paths. Default: [],e.g: ["assets/fonts", "assets/images/dark", ...]
#  path_ignore: []

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/
    - assets/images/new/